/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import clase.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author David
 */
public class InterfazRecuperarPassword extends javax.swing.JDialog {

    ArrayList<Usuario> listaUsuario=new Main().lista();
    /**
     * Creates new form InterfazRecuperarPassword
     */
    public InterfazRecuperarPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbbPregunta = new javax.swing.JComboBox();
        lblPregunta = new javax.swing.JLabel();
        lblRespuesta = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtRespuesta = new javax.swing.JTextField();
        btnRecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Recuperar Password"));

        cbbPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Pregunta Secreta", "¿Cual es el nombre de mi perro?", "¿Cual es mi ciudad de nacimiento?", "¿Cual era mi apodo cuando niño?" }));

        lblPregunta.setText("Pregunta Secreta :");

        lblRespuesta.setText("Respuesta Secreta :");

        lblRut.setText("Rut del Alumno :");

        txtRut.setText("jTextField1");

        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPregunta)
                    .addComponent(lblRut)
                    .addComponent(lblRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRecuperar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbbPregunta, 0, 200, Short.MAX_VALUE)
                        .addComponent(txtRespuesta)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPregunta)
                    .addComponent(cbbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRespuesta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecuperar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mostrarAdvertencia(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public void SetTextoRut(String texto){
        txtRut.setText(texto);
    }
    
    public boolean coincidePreguntaRespuesta(String rut, String pregunta, String respuesta){
        boolean coincide = false;
        try {
            for (Usuario iUsuario : listaUsuario) {
                if(rut.equals(iUsuario.getRut()))
                {
                    if(pregunta.equals(iUsuario.getPregunta())&&respuesta.equals(iUsuario.getRespuesta()))
                    {
                        return true;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("ERROR INESPERADO EN LA CLASE USUARIO = ".concat(e.getMessage()));
        }
        return coincide;
    }
    
    public boolean cambiarContraseña(String rut, String password){
        boolean coincide = false;
        try {
            for (Usuario iUsuario : listaUsuario) {
                if(rut.equals(iUsuario.getRut()))
                {
                    iUsuario.setPassword(password);
                    return true;
                }
            }
        } catch (Exception e) {
            System.out.println("ERROR INESPERADO EN LA CLASE USUARIO = ".concat(e.getMessage()));
        }
        mostrarAdvertencia("HAY ALGO MUY MALO en Cambiar Contraseña");
        return coincide;
    }
    
    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        String rut="";
        String pregunta="";
        String respuesta="";
        String temporalPass="";
        boolean bandera=true;
              
        if(txtRut.getText().isEmpty()){ bandera=false;}
        else {rut=txtRut.getText();}
        if(txtRespuesta.getText().isEmpty()){ bandera=false;}
        else {respuesta=txtRespuesta.getText();}
        if (cbbPregunta.getSelectedIndex()==0) {
            bandera=false;
        } else {
            pregunta=String.valueOf(cbbPregunta.getSelectedItem());
        }
        
        if(bandera==false)
        {
            mostrarAdvertencia("Favor, llene todos los campos");
        }else{
            try{
                if(Usuario.validarRut(txtRut.getText())==false)
                {
                    mostrarAdvertencia("Rut no es valido = ".concat(txtRut.getText()));
                }else{    
                    if(coincidePreguntaRespuesta(rut, pregunta, respuesta))
                    {  
                        temporalPass=JOptionPane.showInputDialog("Ingrese nueva Contraseña Temporal :");
                        cambiarContraseña(rut,temporalPass);
                    }else
                    {
                        mostrarAdvertencia("NO COINCIDEN!!!");
                    }
                }
            }catch(Exception e){
                System.out.println("Error Inesperado de Recuperar Password".concat(e.getMessage()));
            }
        }
    }//GEN-LAST:event_btnRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazRecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazRecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazRecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazRecuperarPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InterfazRecuperarPassword dialog = new InterfazRecuperarPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JComboBox cbbPregunta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPregunta;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblRut;
    private javax.swing.JTextField txtRespuesta;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
