/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemabiblioteca;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import clase.Usuario;
import javax.swing.JOptionPane;
/**
 *
 * @author David
 */
public class InterfazLogin extends javax.swing.JFrame {

    ArrayList<Usuario> listaUsuario=new Main().lista();
    
    /**
     * Creates new form Login
     */
    public InterfazLogin() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRutUsuario = new javax.swing.JTextField();
        txtPasswordUsuario = new javax.swing.JPasswordField();
        btnInicioSesion = new javax.swing.JButton();
        btnRecuperarPassword = new javax.swing.JButton();
        pnlRegistroAlumno = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblPasword = new javax.swing.JLabel();
        lblRepetirPassword = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblRut = new javax.swing.JLabel();
        txtRepetirPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtCarrera = new javax.swing.JLabel();
        cbbCarrera = new javax.swing.JComboBox();
        btnLimpiar = new javax.swing.JButton();
        btnFormularioRegistro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setText("Rut :");

        jLabel2.setText("Password :");

        btnInicioSesion.setText("Iniciar Sesion");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        btnRecuperarPassword.setText("¿Haz olvidado tu password?");
        btnRecuperarPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarPasswordActionPerformed(evt);
            }
        });

        pnlRegistroAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrate"));

        lblNombre.setText("Nombre :");

        lblApellido.setText("Apellido :");

        lblCorreo.setText("Correo Electronico :");

        lblPasword.setText("Contraseña :");

        lblRepetirPassword.setText("Repetir Contraseña :");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lblRut.setText("Rut :");

        txtCarrera.setText("Carrera :");

        cbbCarrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Carrera", "Ingenieria en Informatica" }));

        btnLimpiar.setText("Limpiar Todo");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroAlumnoLayout = new javax.swing.GroupLayout(pnlRegistroAlumno);
        pnlRegistroAlumno.setLayout(pnlRegistroAlumnoLayout);
        pnlRegistroAlumnoLayout.setHorizontalGroup(
            pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                        .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblRut))
                        .addGap(18, 18, 18)
                        .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(lblApellido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellido)
                        .addContainerGap())
                    .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                        .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPasword)
                                    .addComponent(lblCorreo))
                                .addGap(24, 24, 24)
                                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 82, Short.MAX_VALUE))
                                    .addComponent(txtCorreo)))
                            .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRepetirPassword)
                                    .addComponent(txtCarrera))
                                .addGap(18, 18, 18)
                                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cbbCarrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRepetirPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnlRegistroAlumnoLayout.setVerticalGroup(
            pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroAlumnoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRepetirPassword)
                    .addComponent(txtRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarrera)
                    .addComponent(cbbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlRegistroAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar)))
        );

        btnFormularioRegistro.setText("Registrar Alumno");
        btnFormularioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormularioRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlRegistroAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFormularioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInicioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRecuperarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtRutUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicioSesion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecuperarPassword)
                    .addComponent(btnFormularioRegistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRegistroAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void limpiarTodo(){
        txtRutUsuario.setText("");
        txtPasswordUsuario.setText("");
        txtRut.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        cbbCarrera.setSelectedIndex(0);
        txtPassword.setText("");
        txtRepetirPassword.setText("");
    }
    
    public void setVisiblePanelAlumno(boolean valor){
        pnlRegistroAlumno.setVisible(valor);
    }
    public void mostrarAdvertencia(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public boolean existeRut(String rut){
        boolean existeRut = false;
        try {
            for (Usuario iUsuario : listaUsuario) {
                if(rut.equals(iUsuario.getRut()))
                {
                    return true;
                }
            }
        } catch (Exception e) {
            System.out.println("ERROR INESPERADO EN LA CLASE USUARIO = ".concat(e.getMessage()));
        }
        return existeRut;
    }
    
    public boolean coincidePassword(String rut, String password){
        boolean coincide = false;
        try {
            for (Usuario iUsuario : listaUsuario) {
                if(rut.equals(iUsuario.getRut()))
                {
                    if(password.equals(iUsuario.getPassword()))
                    {
                        return true;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("ERROR INESPERADO EN LA CLASE USUARIO = ".concat(e.getMessage()));
        }
        return coincide;
    }
    
    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        
        String rut="";
        String password="";
        if(txtRutUsuario.getText().equals("")||String.valueOf(txtPasswordUsuario.getPassword()).equals("")){
            mostrarAdvertencia("Ingrese su RUT y PASSWORD");
        }   
        else{
            if(Usuario.validarRut(txtRutUsuario.getText())==false)
            {
                mostrarAdvertencia("Rut no es valido = ".concat(txtRutUsuario.getText()));
            }else{
                try {
                    rut = txtRutUsuario.getText();
                    rut = rut.toUpperCase();
                    rut = rut.replace(".", "");
                    rut = rut.replace("-", "");
                    password= String.valueOf(txtPasswordUsuario.getPassword());

                    if(coincidePassword(rut,password)){
                        InterfazPrincipal ventanaPrincipal= new InterfazPrincipal();
                        ventanaPrincipal.setLocationRelativeTo(null);
                        ventanaPrincipal.setVisible(true);
                        this.dispose();
                    }else{
                        mostrarAdvertencia("Su Usuario o Contraseña son Incorrectos");
                    }

                } catch (Exception e) {
                    mostrarAdvertencia("Upss, Ocurrio un error inesperado!!! = " + e.getMessage());
                }
            }
        }
        
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnFormularioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormularioRegistroActionPerformed
        if(btnFormularioRegistro.isSelected())
        {
            this.setSize(520, 370);
            pnlRegistroAlumno.setVisible(true);
        }else
        {
            this.setSize(520, 110);
            pnlRegistroAlumno.setVisible(false);
        }
    }//GEN-LAST:event_btnFormularioRegistroActionPerformed

    private void btnRecuperarPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarPasswordActionPerformed
        InterfazRecuperarPassword recuperar=new InterfazRecuperarPassword(this,true);
        recuperar.SetTextoRut(txtRutUsuario.getText());
        recuperar.setLocationRelativeTo(this);
        recuperar.setVisible(true);
    }//GEN-LAST:event_btnRecuperarPasswordActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        boolean banderaRegistro=true;
        String rut="";
        String nombre="";
        String apellido="";
        String correo="";
        String password="";
        String repetirPass="";
        String carrera="";
        if(txtRut.getText().equals("")){ banderaRegistro=false;} 
        else {
            if(Usuario.validarRut(txtRut.getText())==false)
            {
                mostrarAdvertencia("Rut no es valido = ".concat(txtRut.getText()));
                banderaRegistro=false;
            }else{
                rut=txtRut.getText();
                rut =  rut.toUpperCase();
                rut = rut.replace(".", "");
                rut = rut.replace("-", "");
            }
        }
        if(txtNombre.getText().equals("")){ banderaRegistro=false;} 
        else {nombre=txtNombre.getText();}
        if(txtApellido.getText().equals("")){ banderaRegistro=false;}
        else {apellido=txtApellido.getText();}
        if(txtCorreo.getText().equals("")){ banderaRegistro=false;} 
        else {
            if (txtCorreo.getText().matches("^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\\.[a-zA-Z]{2,4}$")){
                correo=txtCorreo.getText();
            }else{
                mostrarAdvertencia("Ingrese un correo Valido");
                banderaRegistro=false;
            }
        }
        if(String.valueOf(txtPassword.getPassword()).equals("")){ banderaRegistro=false;}
        else {
            
            if(String.valueOf(txtPassword.getPassword()).length()<4)
            {
                mostrarAdvertencia("Contraseña debe ser mayor a 4 caracteres");
                banderaRegistro=false;
            }else{
                password=String.valueOf(txtPassword.getPassword());
            }
        }
        if(String.valueOf(txtRepetirPassword.getPassword()).equals("")){ banderaRegistro=false;} 
        else {
            if(String.valueOf(txtRepetirPassword.getPassword()).equals(String.valueOf(txtPassword.getPassword())))
            {
                repetirPass=String.valueOf(txtRepetirPassword.getPassword());
            }else{
                mostrarAdvertencia("Debe Repetir la misma Contraseña");
                banderaRegistro=false;
            }
        }
        if (cbbCarrera.getSelectedIndex()==0) {
            banderaRegistro=false;
        } else {
            carrera=String.valueOf(cbbCarrera.getSelectedItem());
        }
        
        if(banderaRegistro==false)
        {
            mostrarAdvertencia("Favor, llene todos los campos");
        }else{
            if(existeRut(rut)==false){
                Usuario registroUsuario= new Usuario(rut, nombre, apellido, correo, password, carrera);
                listaUsuario.add(registroUsuario);
                mostrarAdvertencia("Registro Completado Satisfactoriamente");
                limpiarTodo();
            }else{
                mostrarAdvertencia("RUT ya existe en la Base de Datos");
            }
        }
        
        for (Usuario listaUsuario1 : listaUsuario) {
            System.out.println(listaUsuario1.getRut());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTodo();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFormularioRegistro;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRecuperarPassword;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cbbCarrera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPasword;
    private javax.swing.JLabel lblRepetirPassword;
    private javax.swing.JLabel lblRut;
    private javax.swing.JPanel pnlRegistroAlumno;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordUsuario;
    private javax.swing.JPasswordField txtRepetirPassword;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtRutUsuario;
    // End of variables declaration//GEN-END:variables
}
